
		<div id="isi">
			<div class="isipostingall">
				<h2>Nineteen Eighty-Four</h2>
			<img src="https://media.karousell.com/media/photos/products/2018/10/14/ebook_george_orwell__1984_1539491850_8af0afd6_progressive.jpg" class="gambarposting1">
			<ul>
			    <h3>- Identitas Buku</h3>
			</ul>
				<p> Judul Buku      : Nineteen Eighty-Four<br>
                    Penulis         : George Orwell<br>
                    Penerbit        : Bentang Pustaka<br>
                    Tebal Buku      : 408 halaman
                </p>
			<ul>
			    <h3>- Rangkuman Buku</h3>
			</ul>
				<p>Novel “1984” bercerita tentang suatu masa di sekitar tahun 1984. Orwell menggambarkan masa itu sebagai masa yang penuh penderitaan. Dalam semesta “1984”, dunia dibagi menjadi tiga poros kuasa; Oceania, Eurasia, dan Eastasia. Setiap negara dipimpin oleh satu partai. Mereka semua berhaluan sosialis. Setiap negara juga menerapkan sistem totalitarian. Novel ini fokus menceritakan Oceania, khususnya London dimana sang tokoh utama hidup. Oceania dipimpin oleh Big Brother (Bung Besar) yang wajahnya tertera di poster-poster di berbagai penjuru negara. Sistem kediktatoran yang diterapkan membuat semua warganya harus tunduk dan patuh. Kedisiplinan ini sifatnya menyeluruh. Mulai dari jadwal bangun tidur, hiburan, buku yang dibaca, bahkan ekspresi muka dan pikiran.</p>
				<p>Teleskrin adalah kunci Partai dan Bung Besar melanggengkan kekuasaannya. Selain sebagai media doktrinasi, teleskrin adalah sebuah alat yang efektif untuk mengendalikan tingkah laku seseorang. Teleskrin adalah sarana yang efektif dan efisien dalam mempertahankan kekuasaan, menebar ketakutan, dan memodifikasi tingkah laku. Dengan adanya teleskrin, pemerintah Oceania dapat segera mencegah adanya indikasi penyelewengan atau pemberontakan dari warganya. Teleskrin juga sekaligus membuat warga Oceania yang mempunyai pandangan berbeda takut menyuarakan gagasannya dan menyimpannya agar tak kena hukuman. Dengan begitu, tidak akan ada gerakan kolektif menentang pemerintahan, sebab bibit perlawanan sudah dibabat pada level individual.</p>
				<p>Konsep teleskrin dapat dibilang menyerupai konsep Panopticon yang dicetuskan oleh Jeremy Bentham lalu kemudian dikembangkan oleh Michel Foucault. Dalam Discipline and Punish: The Birth of The Prison, Foucault menjelaskan bahwa panopticon adalah sebuah rancangan arsitektur penjara yang dibuat Jeremy Bentham untuk memaksimalkan fungsi penjara. Dalam skema penjara panopticon, penjara dibuat berbentuk lingkaran dan di bagian tengahnya terdapat menara pusat. Sel penjaranya berada di pinggir lingkaran. Pada setiap sel, terdapat jendela yang memungkinkan menara pusat untuk melihatnya. Namun, sang tahanan penjara tidak dapat mengetahui apakah dia sedang diawasi atau tidak. Maka, ia akan selalu bertindak seakan-akan ia diamati.
					Ada dua aspek yang penting; visibile (terlihat) dan unverifiable (tak bisa dipastikan). Visible berarti subjek yang diawasi atau tahanan penjara melihat dan tahu bahwa ada yang mengamatinya. Unverifiable berarti subjek tidak tahu apakah ia sedang diawasi atau tidak. Dengan perasaan selalu diawasi, Foucault berkata bahwa power (kuasa) akan bekerja secara otomatis. Cara kerja teleskrin dan panopticon sama; menggunakan pengawasan untuk memaksa subjek yang diawasi berperilaku sesuai yang diharapkan. Dalam aspek visible, teleskrin dan panopticon mempunyai kesamaan. Keduanya sama-sama dapat dilihat oleh subjek yang diawasi.</p>
				<p>Gagasan pengawasan yang dihadirkan Orwell mempunyai kesamaan dengan internet. Saat ini, internet juga dilakukan untuk pengawasan. Namun, pola kerja pengawasan yang ada di internet berbeda dengan teleskrinnya Orwell dan panopticon-nya Foucault. Hal yang membedakan panopticon dan teleskrin dengan internet adalah unsur visible. Carlo Bordoni, seorang pakar sosiologi cum jurnalis asal Italia, mengatakan bahwa, “The new Panopticon already exists, it is the web: surveillance is being carried out but not visibly so, and with the maximum discretion.”[1] Bordoni mengutip Zygmunt Bauman, pakar sosiologi Polandia, menjelaskan bahwa jaringan global di era sekarang membuat kita semua dapat terlihat dan dapat diobservasi oleh kekuatan yang tak terlihat.</p>
				<p>Saat ini, kita tahu bahwa seluruh aktivitas manusia di internet terbuka. Kita diawasi. Setiap jejak langkah kita di internet dapat dilihat. Ada dua agen yang menjadi pengawas; kapitalis dan pemerintah. Kapitalis atau korporasi besar di internet menggunakan situsnya sebagai alat pengawas dan pengeruk data. Tercatat 50% dari situs populer di internet menggunakan cookies untuk mengeruk informasi. Berbagai situs di internet yang sering kita gunakan seperti Google, Facebook dan Twitter, mengeruk informasi pribadi kita untuk kepentingan mereka. Data pribadi yang didapatkan digunakan sebagai informasi untuk mengoptimalkan iklan. Informasi pribadi digunakan untuk mencari preferensi pribadi sehingga iklan dapat bekerja dengan tepat sasaran.</p>
				<p>Selain kapitalis, pemerintah juga melakukan hal yang sama. Pada 2013 lalu, Edward Snowden mengungkapkan ke beberapa jurnalis tentang aktivitas National Security Agency (NSA). Amerika Serikat yang mengawasi berbagai hal di internet. Pemerintah dengan pengawasan melalui internet dapat “menelanjangi” warganya dengan mengetahui segala informasi dan aktivitasnya di internet. Pengawasan di era internet seperti ini berbeda tujuannya dengan pengawasan panopticon atau teleskrin. Pengawasan panopticon dan teleskrin digunakan untuk membenahi perilaku seseorang. Sedangkan, pengawasan saat ini (internet) digunakan untuk mengeruk informasi sebanyak-banyaknya untuk kemudian dimanfaatkan. Yang dapat memanfaatkan informasi tersebut tentu yang mempunyai akses kepada informasi itu; kapitalis dan pemerintah. Keduanya memanfaatkan data pribadi untuk keperluannya masing-masing.</p>
				<p>Kapitalis menggunakan informasi yang didapat untuk meningkatkan tingkat keuntungan. Data-data pribadi digunakan untuk keperluan iklan. Informasi seperti lokasi, nama, hobi, aktivitas pencarian, musik yang sering didengar, video yang sering ditonton, semua dikeruk dan digunakan dalam rangka meningkatkan penghasilan. Semua data itu digunakan untuk mengetahui apa yang kita pikirkan. Lalu, mereka bisa mengiklankan produk yang sesuai dengan keinginan kita. Kapitalis internet mendapatkan sarana meningkatkan pendapatan secara cuma-cuma melalui informasi yang kita tinggalkan di internet.</p>
                <p>Dengan membaca “1984” dan membenturkannya dengan keadaan saat ini kita bisa menarik satu gagasan yang menarik. Kita mungkin tidak hidup dalam rezim totaliter seperti di “1984”. Tidak ada teleskrin di sekitar kita. Tidak ada Bung Besar yang mengintai kita. Namun, apakah keadaan sekarang lebih baik dari apa yang di-”ramal”kan Orwell? Kita memang tidak hidup di bawah Bung Besar, tapi kita hidup di bawah dua penguasa; kapitalis dan pemerintah. Dengan kenyataan bahwa seluruh tindakan kita di dunia maya tidak lepas dari intaian dua mata itu.</p>
			</div>
		</div>
			
	</div>
	
	</div>
