
		<div id="isi">
			<div class="isipostingall">
				<h2>A Little History of the World</h2>
			<img src="https://tse3.mm.bing.net/th?id=OIP.IfT8u_WRj9vWpqRmaVogzAAAAA&pid=Api&P=0&w=300&h=300" class="gambarposting1">
			    <h3>Synopsis Buku</h3>
			</ul>
				<p>A Little History of the World contains forty chapters, each of which focuses on a specific period in human history. Gombrich doesn’t attempt to describe any of these events in great detail—instead, he highlights the breadth of our accomplishments across the ages. It is designed to be read as a narrative, not as an encyclopedia. The book is not meant to replace academic texts or reference books. Although the target audience is middle grade to young adult, older readers may also enjoy the content.</p>
				<p>Given the scope of the work, Gombrich admits that he couldn’t include every significant event in world history. He confines his account to Europe, from pre-historic eras to the First World War. Later editions also include a chapter on the Second World War that he later added to the text. Critics point out that there is almost nothing about Africa and very little about the Americas, Japan, China, or India.</p>
				<p>In the first chapter, “Once Upon A Time,” Gombrich explains that this is not simply a history lesson. It is the history of us, how we came to be here, and the world we have inherited. He touches on Earth’s origins, the earliest forms of life, the dinosaurs, and how land formed from the sea. However, Gombrich points out that we can go only so far back in time before it becomes unknowable; he begins the book in earnest from the Stone Age onwards.</p>	
				<p>Gombrich explains the difference between prehistory and history. Prehistory is no less important, but we know so little about it because it is impossible to date anything accurately. History begins in 3,100 BC in Egypt because this is the first time that we can say when and where something significant happened. We know that clothes, tools, weapons, and other inventions came before 3,100 BC, but it is impossible to say when.</p>	
				<p>The first empire, then, covered in A Little History of the World, is Ancient Egypt. Gombrich discusses the importance of the Nile, the hieroglyphs, how the Egyptians, structured their society around resources, and the role of the pharaohs. The Egyptians paved the way for many later civilizations—including, for example, Ancient Rome, which is also covered in the book.</p>
				<p>In chapter six, “I C-A-N R-E-A-D,” Gombrich examines one of the most important developments in our history—that is, language and the alphabet. He considers why we started writing in the first place, the freedoms it offered us, and how much easier it is to understand ancient civilizations by reading what they wrote. Their letters, edicts, poems, and historical texts all tell a story about what mattered to them; this is very helpful for modern-day scholars and historians.</p>
				<p>Gombrich covers events that are especially exciting for young people, such as the history of sport and the Olympic games. He looks at how some of the events we watch today originated in Ancient Greece, and how important sporting achievements were in some civilizations. Gombrich offers children an overview of how societies can be shaped around culture and entertainment.</p>	
				<p>As this is a history of the world, Gombrich doesn’t avoid discussing war and significant battles over the ages. He covers everything from the destruction of Israel to the conquests of Alexander the Great, reflecting on the role that religion played in every conflict. He also touches upon Chinese scholars and philosophers, their influence on Western thought, and how spiritual beliefs can determine the direction of civilization.</p>	
				<p>Gombrich devotes many chapters to Christianity and how the religion shaped Europe, from Christianity’s earliest origins to the present day. He covers challenges to Christianity in some detail, from the Christian persecutions in Rome to the Crusades. Gombrich doesn’t offer opinions as to which side is “right” and which side is “wrong”—he only presents the facts, letting readers decide what to think.</p>	
				<p>Not everything in A Little History of the World focuses on war and conquest. Gombrich discusses the birth of literature, theatre, art, and culture, and he dedicates chapters to developments such as the Enlightenment, socialist revolutions, the Industrial Revolution, and human rights.</p>	
				<p>Gombrich concludes A Little History of the World by reflecting on what history can teach us about the present, and how we can prepare for the future. We are living history right now, and it is up to us how we shape it for later generations. Gombrich hopes that readers, upon finishing A Little History of the World, will be inspired to undertake further study in some of the areas discussed in the book.</p>	
			</div>
		</div>
		
	</div>
	
	</div>
